# Generated by Django 4.1.10 on 2024-02-18 00:48

from django.db import migrations, models
import django.db.models.deletion
import main.models
import main.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Категорию информации',
                'verbose_name_plural': 'Категории информации',
            },
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, help_text='Если "Внутренняя ссылка" не указана, будет применен абсолютный путь infopage/<slug:slug>/', null=True, verbose_name='slug')),
                ('clue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказка')),
                ('internal_link', main.models.InternalURLField(blank=True, help_text='Внутренние ссылки должны соответствовать urls.name моделей', max_length=255, null=True, verbose_name='Внутренняя ссылка')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка')),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('category_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_page', to='main.categoriesinfo', verbose_name='Категория InfoPage')),
            ],
        ),
        migrations.CreateModel(
            name='ContentInfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема/Вопрос')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=main.utilities.get_img_file_path, verbose_name='Изображение')),
                ('image_style', models.CharField(blank=True, help_text='... width="200" height="255" align="right" дополнительно см. https://htmlbook.ru/html/IMG', max_length=255, null=True, verbose_name='Стиль')),
                ('info_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_ip', to='main.infopage', verbose_name='Информационная страница')),
            ],
        ),
    ]
