# Generated by Django 4.1.10 on 2024-02-18 07:42

from django.db import migrations, models
import django.db.models.deletion
import main.models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('grid_class', models.CharField(choices=[('1-й ряд, 1-ая колонка из 4-х', 'r1c1'), ('1-й ряд, 2-ая колонка из 4-х', 'r1c2'), ('1-й ряд, 3-я колонка из 4-х ', 'r1c3'), ('1-й ряд, 4-ая колонка из 4-х', 'r1c4'), ('2-й ряд', 'r2c1'), ('3-й ряд', 'r3c1'), ('4-й ряд', 'r4c1')], max_length=50)),
            ],
            options={
                'verbose_name': 'Группа Footer',
                'verbose_name_plural': 'Группа Footer',
            },
        ),
        migrations.AlterModelOptions(
            name='infopage',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информация'},
        ),
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, help_text='Если "Внутренняя ссылка" не определена и указан slug, будет применен абсолютный путь infopage/<slug:slug>/', null=True, verbose_name='slug')),
                ('clue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказка')),
                ('internal_link', main.models.InternalURLField(blank=True, help_text='Относительные ссылки должны соответствовать urls.name моделей', max_length=255, null=True, verbose_name='Относительная ссылка')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка')),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('cat_footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basement_group', to='main.categoriesfooter', verbose_name='Категория Footer')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема/Вопрос')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=main.utilities.get_img_file_path, verbose_name='Изображение')),
                ('image_style', models.CharField(blank=True, help_text='... width="200" height="255" align="right" дополнительно см. https://htmlbook.ru/html/IMG', max_length=255, null=True, verbose_name='Стиль')),
                ('footer_links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_links', to='main.infopage', verbose_name='Информационная страница')),
            ],
            options={
                'verbose_name': 'Контент ссылки',
                'verbose_name_plural': 'Контент ссылок',
            },
        ),
    ]
