# Generated by Django 4.1.10 on 2024-02-18 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categoriesfooter_alter_infopage_options_footerlinks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesfooter',
            options={'verbose_name': 'Группу Footer', 'verbose_name_plural': 'Группы Footer'},
        ),
        migrations.AlterField(
            model_name='categoriesfooter',
            name='grid_class',
            field=models.CharField(choices=[('r1c1', '1-й ряд, 1-ая колонка из 4-х'), ('r1c2', '1-й ряд, 2-ая колонка из 4-х'), ('r1c3', '1-й ряд, 3-ая колонка из 4-х'), ('r1c4', '1-й ряд, 4-ая колонка из 4-х'), ('r2c1', '2-й ряд'), ('r3c1', '3-й ряд'), ('r4c1', '4-й ряд')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='footer_links',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_links', to='main.footerlinks', verbose_name='Информационная страница'),
        ),
    ]
