# Generated by Django 4.1.10 on 2024-02-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_contentinfopage_info_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesfooter',
            options={'verbose_name': 'Группу (Категорию)', 'verbose_name_plural': 'Группы (Категории)'},
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='image_style',
        ),
        migrations.AddField(
            model_name='contentpage',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись изображения'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='image_position',
            field=models.CharField(blank=True, choices=[('img_left', 'Изображение по левому краю'), ('img_left', 'Изображение по центру'), ('img_right', 'Изображение по правому краю')], default='img_left', max_length=255, null=True, verbose_name='Позиция изображения'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='image_width',
            field=models.CharField(blank=True, choices=[('img25', 'Ширина изображения 25%'), ('img30', 'Ширина изображения 30%'), ('img50', 'Ширина изображения 50%'), ('img100', 'Ширина изображения 100%')], default='img25', max_length=255, null=True, verbose_name='Ширина изображения'),
        ),
    ]
