# Generated by Django 4.1.10 on 2024-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_contentpage_image_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='display_title',
            field=models.BooleanField(default=False, verbose_name='Отображать заголовок'),
        ),
    ]
